### ISSUE TITLE
Git credentials when cloning?

### ISSUE THREAD

**Issue by patricksebastien** [omlins/JustSayIt.jl#6]
Hi,
```
add https://github.com/omlins/JustSayIt
    Cloning git-repo `https://github.com/omlins/JustSayIt`
Username for 'https://github.com': 
Password for 'https://github.com':
```
Not sure why it's asking for the credentials, but anyway trusting the script I am entering my user and password but still failing:
`ERROR: failed to clone from https://github.com/omlins/JustSayIt, error: GitError(Code:EUSER, Class:Callback, Aborting, user cancelled credential request.)`

**Comment by omlins** [comment]
Hi @patricksebastien, thanks for your interest in JustSayIt. You are missing the ".jl" at the end of the repository name (so, I guess, github thinks you want to access a private repository with that name and asks for username and password). If you do
```julia
add https://github.com/omlins/JustSayIt.jl
```
then it should work - it should not ask for user name and password.

**Comment by patricksebastien** [comment]
Thanks cloning!
