### ISSUE TITLE
Keyboard.type fails with "insecure command argument recognition"

### ISSUE THREAD

**Issue by pfitzseb** [omlins/JustSayIt.jl#88]
Following the usage instructions at https://omlins.github.io/JustSayIt.jl/stable/usage/#Fast-command-programming-with-voice-argument-functions, `type` fails:
```
julia> start(commands=commands, max_speed_subset=["ma", "select", "okay", "middle", "right", "double", "triple", "copy", "upwards", "downwards", "take"])
[ Info: JustSayIt: I am initializing...
[ Info: Listening for commands in English (United States) (say "sleep JustSayIt" to put me to sleep; press CTRL+c to terminate)...
[ Info: Starting command: click_left (latency: 11 ms)
[ Info: Starting command: type
[ Info: Command `type` aborted: insecure command argument recognition.
^C[ Info: Terminating JustSayIt...
[ Info: Stopped listening for commands.
```

Ref https://github.com/JuliaCon/proceedings-review/issues/121.

**Comment by omlins** [comment]
@pfitzseb : thanks for the issue. However, I don't think the link you posted points points to the right example. Could you please point to the right one?

Then, it might be here rather a documentation issue then a software issue, i.e., the documentation could potentially be clearer. Concretely, after starting the command "type" you need to specify the type mode; else it will abort as shown in your snippet. To see the available type modes say "help type" (more info about help is found here: https://omlins.github.io/JustSayIt.jl/stable/usage/#Help-on-commands-callable-by-voice)

**Comment by pfitzseb** [comment]
Oh, gotcha. Definitely user error, I didn't realize `type` takes a second argument for some reason. The error message isn't particularly helpful though :)
